workite/keeper/urls.py
# -*- coding: utf-8 -*-
"""workite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.contrib import admin

from django.conf.urls import url

from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = 'keeper'

urlpatterns = [
    # url(r'^1/', views.basic_one),
    url(r'^test_select/', views.test_select),
    url(r'^keepermarkeredit/', views.keepermarker),
    url(r'^keepermarkeredit_add/', views.keepermarkeredit_add),
    url(r'^keepermarkeredit_delete/(?P<marker_id>\d+)/', views.keepermarkeredit_delete),
    url(r'^keepermarkereedit/(?P<marker_id>\d+)/', views.keepermarkereedit),
    url(r'^keepermarker/', views.keepermarker),
    url(r'^newkeeper/', views.newkeeperform),
    url(r'^addkeeper/', views.addkeeper),
    url(r'^editkeeper/(?P<keeper_id>\d+)/', views.editkeeperform),
    url(r'^theeditkeeper/(?P<keeper_id>\d+)/', views.editkeeper),
    url(r'^deletekeeper/(?P<keeper_id>\d+)/', views.deletekeeper),
    url(r'^keeper/all/$', views.keepers),
    url(r'^keeper/get/(?P<keeper_id>\d+)/(?P<page_number>\d+)/', views.keeper),
    url(r'^keeper/get/(?P<keeper_id>\d+)/', views.keeper),
    url(r'^keeper/addfeedback/(?P<keeper_id>\d+)/$', views.addfeedback),
    url(r'^keepers_clean_search/', views.keepers_clean_search),
    url(r'^page/(\d+)/$', views.keepers),
    url(r'^page/(\d+)/(?P<searchlabe>\w+)/', views.keepers),
    url(r'error/(?P<error_text>\w+)/', views.Error),
    url(r'^$', views.keepers),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

workite/workite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('keeper.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('loginsys.urls')),


]

workite/keeper/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.widgets import CKEditorWidget

# Create your models here.

class SearchLabelKeeper(models.Model):
    def __str__(self):
        return self.searchlabelkeeper_marker
    class Meta():
        db_table = 'searchlabelkeeper'
    searchlabelkeeper_marker = models.CharField(max_length=200, verbose_name='Поисковая метка', unique=True)

class Keeper(models.Model):
    def __str__(self):
        return self.keep_title
    class Meta():
        db_table = 'keep'

    keep_title = models.CharField(max_length=200, verbose_name='Название статьи')
    # keep_text = models.TextField(verbose_name='Текст статьи')
    keep_text = RichTextUploadingField(verbose_name='Текст статьи')
    keep_data = models.DateTimeField(null=True)
    keep_hashTag = models.ManyToManyField(SearchLabelKeeper)


class Feedback(models.Model):
    def __str__(self):
        return self.feedback_text
    class Meta():
        db_table = 'feedback'

    feedback_text = models.TextField(verbose_name='Комментарий') #verbose_name - читаемое поле
    feedback_data = models.DateTimeField(null=True)
    feedback_keeper = models.ForeignKey(Keeper)
    feedback_from = models.ForeignKey(User)

class Suggestions(models.Model):
    def __str__(self):
        return self.suggestions_text
    class Meta():
        db_table = 'suggestions'

    suggestions_text = models.TextField(verbose_name='Исправления') #verbose_name - читаемое поле
    suggestions_data = models.DateTimeField(null=True)
    suggestions_keeper = models.ForeignKey(Keeper)
    suggestions_from = models.ForeignKey(User)



class KeeperStatus(models.Model):
    def __str__(self):
        return self.keeper_status_text
    class Meta():
        db_table = 'keeperstatus'

    keeper_status_text = models.CharField(max_length=100, verbose_name='Статус статьи')

workite/keeper/forms.py
# -*- coding: utf-8 -*-
__author__ = 'macpro'

from django.forms import ModelForm
from django import forms
from keeper.models import Feedback, Keeper, SearchLabelKeeper

from ckeditor.widgets import CKEditorWidget




class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        #fields =  '__all__'
        fields = ['feedback_text']

class KeeperForm(ModelForm):
    class Meta:
        content = forms.CharField(widget=CKEditorWidget())
        model = Keeper
        fields = ['keep_text']

class SearchLabelKeeperForm(ModelForm):
    class Meta:
        model = SearchLabelKeeper
        fields = '__all__'

# from post.models import Post
#
# class PostAdminForm(forms.ModelForm):
#     content = forms.CharField(widget=CKEditorWidget())
#     class Meta:
#         model = Post
#
# class PostAdmin(admin.ModelAdmin):
#     form = PostAdminForm
#
# admin.site.register(Post, PostAdmin)

workite/keeper/views.py
# -*- coding: utf-8 -*-
from django.http.response import HttpResponse, Http404
from django.http.request import HttpRequest
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render_to_response, redirect
from keeper.models import Keeper, Feedback, Suggestions, SearchLabelKeeper
from django.core.exceptions import ObjectDoesNotExist
from django.middleware import csrf
from django.views.decorators.csrf import csrf_protect, requires_csrf_token, csrf_exempt
from django.core.paginator import Paginator
from django.contrib import auth
from keeper.forms import FeedbackForm, KeeperForm, SearchLabelKeeperForm
from datetime import datetime, date, time
from django.db.models import Q, Count
from operator import __or__ as OR
from operator import __and__ as AND
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import user_passes_test
from functools import reduce
from django.contrib.auth.models import User, Group
from itertools import chain
# from .widgets import CKEditorWidget

from django.shortcuts import render
from django import forms
# Create your views here.


def basic_one(request):
    view = "<span style='color: red;'>Заявку могут оставить только зарегистрированные пользователи!</span>"
    html = "<html><body> this is %s view</body></html>" % view
    return HttpResponse(html)
def group_required(*group_names):
    def in_groups(user):
        if user.is_authenticated():
            if user.is_superuser or bool(user.groups.filter(name__in=group_names)):
                return True
        return False
    return user_passes_test(in_groups)

@csrf_protect
def test_select(request):
    all_SearchLabelKeeper = SearchLabelKeeper.objects.all()
    args = {}
    args = {}
    # args['keeper_id'] = keeper_id
    # args['KeeForm'] = form
    args['username'] = auth.get_user(request).username
    args['SearchLabelKeepers'] = SearchLabelKeeper.objects.all()
    # args['keeper_search'] = article.keep_hashTag.all()
    # args['keep_title'] = article.keep_title

    args['SearchLabelKeepers'] = all_SearchLabelKeeper
    if request.POST:
        args = {}
        args['SearchLabelKeepers'] = all_SearchLabelKeeper
        if request.POST.getlist('search_attribute') or request.POST.getlist('search_and_only'):
            search_and_l = ''.join(request.POST.getlist('search_attribute'))
            args['search_attribute'] = request.POST.getlist('search_attribute')
            args['search_and_only'] = request.POST.getlist('search_and_only')

            all_keeper = Keeper.objects.all()
            for search_i in request.POST.getlist('search_attribute'):
                all_keeper = all_keeper.filter(keep_hashTag=SearchLabelKeeper.objects.filter(searchlabelkeeper_marker=search_i))
            # all_keeper = all_keeper.filter(keep_hashTag=None)# без тегов
            # qss = Keeper.keep_hashTag.through.objects.values('keeper_id').annotate(count=Count('keeper_id')).filter(count=len(request.POST.get('hero[]')))
            # qsslen = []
            # if request.POST.get('search_and_only') == 'only_and':
            #
            #     for keeper_id_filter in qss.values('keeper_id'):
            #         qsslen.append(keeper_id_filter['keeper_id'])
            #     all_keeper = all_keeper.filter(id__in=qsslen)
            args['keeps'] = all_keeper
            # args['test2'] = auth.get_user(request).username
            # args['test2'] = User.objects.filter(groups__name='admin')
            for grup in Group.objects.filter(user=User.objects.filter(username=auth.get_user(request).username)):
                args['test2'] = Group.objects.filter(name='admin')
                if str(grup) == 'admin':
                    args['grups'] = 'asdasd'

                    # args['test2'] = request.POST.getlist('search_and_only')

                    # if search_i.keep_hashTag.all().count() < 2:
                    #     all_keeper = all_keeper.filter(keep_hashTag__searchlabelkeeper_marker__contains=search_i)
                #     args['keeps'] = all_keeper
                # all_keeper = all_keeper.filter(keep_hashTag=SearchLabelKeeper.objects.get(id=2)).distinct('keep_hashTag')
            # args['keeps'] = all_keeper
            # args['keeps'] = keep_search_or_and(search_and=request.POST.getlist('hero[]'), search_or=request.POST.getlist('hero2[]'), search_text=request.POST['search_text'])
        # if request.POST.getlist('hero[]'):
        #     serand = request.POST.getlist('hero[]')
        #     args['keeps'] = keep_search_and(serand)
        # elif request.POST.getlist('hero2[]'):
        #     seror = request.POST.getlist('hero2[]')
        #     args['keeps'] = keep_search_or(seror)

    # return render_to_response('test_select.html', args)
    return render(request, 'test_select.html', args)


def keep_search_or_and(search_or_and_only, search_attribute, search_text):

    if search_or_and_only == 'search_and':
        all_keeper = Keeper.objects.all()
        for search_i in search_attribute:
            all_keeper = all_keeper.filter(keep_hashTag=SearchLabelKeeper.objects.filter(searchlabelkeeper_marker=search_i))
    elif search_or_and_only == 'search_or':
        lst = []
        for search_i in search_attribute:
            lst.append(Q(keep_hashTag=SearchLabelKeeper.objects.filter(searchlabelkeeper_marker=search_i)))
        all_keeper = Keeper.objects.filter(reduce(OR, lst)).distinct()
    elif search_or_and_only == 'search_and_only':
        lst = []
        all_keeper = Keeper.objects.all()
        for search_i in search_attribute:
            all_keeper = all_keeper.filter(keep_hashTag=SearchLabelKeeper.objects.filter(searchlabelkeeper_marker=search_i))
            qss = Keeper.keep_hashTag.through.objects.values('keeper_id').annotate(count=Count('keeper_id')).filter(
                count=len(search_attribute))
            for keeper_id_filter in qss.values('keeper_id'):
                lst.append(keeper_id_filter['keeper_id'])
            all_keeper = all_keeper.filter(id__in=lst) # только эти

    else:
        all_keeper = Keeper.objects.all()

    all_keeper = all_keeper.filter(Q(keep_text__icontains=search_text) | Q(keep_title__icontains=search_text))
    return(all_keeper)
# @permission_required('', login_url='/auth/login/')
# @group_required('admin', 'admin2')
@csrf_protect
def keepers(request, page_number=1):
    args = {}
    args['username'] = auth.get_user(request).username
    args['login'] = auth.get_user(request).username
    args['SearchLabelKeepers'] = SearchLabelKeeper.objects.all()
    if request.POST:
        if request.POST.getlist('search_attribute') or \
                request.POST.getlist('search_text') or \
                request.POST.get('search_or_and_only'):
            all_keeper = keep_search_or_and(search_attribute=request.POST.getlist('search_attribute'),
                                            search_or_and_only=request.POST.get('search_or_and_only'),
                                            search_text=request.POST['search_text'])
            request.session.set_expiry(6000)
            args['search_attribute'] = request.session["search_attribute"] = request.POST.getlist('search_attribute')
            args['search_text'] = request.session["search_text"] = request.POST['search_text']
            args['search_or_and_only'] = request.session["search_or_and_only"] = request.POST.get('search_or_and_only')
            all_keeper = all_keeper.order_by('-keep_data')
            current_page = Paginator(all_keeper, 4)
            args['keeps'] = current_page.page(page_number)
            args['page_prior'] = int(page_number) - 4
            args['page_afterwards'] = int(page_number) + 4
            args['num_pages_'] = int(current_page.num_pages) - 4

    else:
        if ("search_attribute" in request.session) or \
                ("search_text" in request.session) or \
                ("search_or_and_only" in request.session):
            all_keeper = keep_search_or_and(search_attribute=request.session["search_attribute"],
                                            search_text=request.session["search_text"],
                                            search_or_and_only=request.session["search_or_and_only"])
            args['search_attribute'] = request.session["search_attribute"]
            args['search_text'] = request.session["search_text"]
            args['search_or_and_only'] = request.session["search_or_and_only"]
        else:
            all_keeper = Keeper.objects.all().order_by('-keep_data')

        all_keeper = all_keeper.order_by('-keep_data')
        current_page = Paginator(all_keeper, 4)
        args['keeps'] = current_page.page(page_number)
        args['page_prior'] = int(page_number) - 4
        args['page_afterwards'] = int(page_number) + 4
        args['num_pages_'] = int(current_page.num_pages) - 4

    return render(request, 'Keepers.html', args)

def keepers_clean_search(request):
    request.session["search_attribute"] = []
    request.session["search_text"] = ""
    request.session["search_or_and_only"] = "search_and"
    return redirect('/')

@csrf_protect
def keeper(request, keeper_id=1, page_number=1):
    article = Keeper.objects.get(id=keeper_id)
    all_feedbacks = Feedback.objects.filter(feedback_keeper_id=keeper_id).order_by('-feedback_data')
    current_page = Paginator(all_feedbacks, 5)
    feedback_form = FeedbackForm
    args = {}
    # args.update(csrf(request))
    args['keep'] = article
    args['feedbacks'] = current_page.page(page_number)
    args['FedForm'] = feedback_form
    args['username'] = auth.get_user(request).username
    args['keeper_search'] = article.keep_hashTag.all()
    # args['usergroup'] = auth.get_user(request)
    return render(request, 'Keeper.html', args)


def addfeedback(request, keeper_id):
    if request.POST:
        FedForm = FeedbackForm(request.POST)
        if FedForm.is_valid():

workite/keeper/templates/EditKeeper.html
{% extends 'main.html' %}
{% load staticfiles %}
{% block keeper %}

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
        <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script>
        $(document).ready(function() {
                $("#button_load_earchLabelKeepers").click(function () {
                        $("#id_SearchLabelKeepers").load(location.href + " #id_SearchLabelKeepers>*", "");

                });
        });
</script>

<div class="medium-2 large-offset-0 columns">
                <button id="button_load_earchLabelKeepers" class="button">Обновить список</button>
</div>
<div class="columns medium-2 large-offset-0 ">
                <a href="/keepermarkeredit/" class="button" onclick="newMyWindow1(this.href); return false;">Список тегов</a>
                <script>
                function newMyWindow1(href) {
                  var d = document.documentElement,
                      h = 500,
                      w = 500,
                      myWindow = window.open(href, 'myWindow', 'scrollbars=1,height='+Math.min(h, screen.availHeight)+',width='+Math.min(w, screen.availWidth)+',left='+Math.max(0, ((d.clientWidth - w)/2 + window.screenX))+',top='+Math.max(0, ((d.clientHeight - h)/2 + window.screenY)));

                      // абзац для Chrome
                      if (myWindow.screenY >= (screen.availHeight - myWindow.outerHeight)) {myWindow.moveTo(myWindow.screenX, (screen.availHeight - myWindow.outerHeight))};
                      if (myWindow.screenX >= (screen.availWidth - myWindow.outerWidth)) {myWindow.moveTo((screen.availWidth - myWindow.outerWidth), myWindow.screenY)};

                }
                </script>
        </div>
    <form action="/theeditkeeper/{{keeper_id}}/" method="post">
        {% csrf_token %}
        <div>
            <p style="word-break: break-all;">Хэштеги: {%for keeper_search_i in keeper_search%}
            {{keeper_search_i}}
            {%endfor%}</p>
        </div>
        <div id="id_SearchLabelKeepers">

        <select size="4" multiple="multiple" name="search_attribute" required>
            {% for marker in SearchLabelKeepers %}
                <option {%if marker in keeper_search %}
                        selected
                        {%endif%}
                        value="{{marker.searchlabelkeeper_marker}}">{{marker.searchlabelkeeper_marker}}</option>
            {% endfor %}
        </select>
        </div>
        <div>
            <p style="word-break: break-all;">Название статьи: {{keep_title}}</p>
        </div>
        <div>
            {{KeeForm}}
        </div>
        <input type="submit" class="button" value="Изменить статью">
        <h6><p class="text-right"><a href="/keepermarkeredit/">Список тегов</a> </p> </h6>
    </form>

{% endblock %}

workite/keeper/templates/Error_keeper.html
{% load staticfiles %}
{% block keeper %}
<link rel="stylesheet" type="text/css" href="{% static "/css/foundation.css" %}">
<h2>Ошибка! </h2><h4><p>{{Error_text}}</p></h4>
<img src="{% static "kote.gif" %}" width="300px" height="300px ">
{% endblock %}

workite/keeper/templates/Keeper.html
{% extends 'main.html' %}
{% block keeper %}
        <div>
            <p style="word-break: break-all;">Хэштеги: {%for keeper_search_i in keeper_search%}
            {{keeper_search_i}}
            {%endfor%}</p>
        </div>
    {% load tz %}
    {% timezone "Europe/Moscow" %}
<h6>{{keep.keep_title}}</h6><h6><p class="text-right"><a href="/editkeeper/{{keep.id}}/">Изменить</a></p></h6>
{{usergroup}}
<!--</h6><h6><p class="text-right"><a href="/deletekeeper/{{keep.id}}/">Удалить</a></p></h6>-->
</h6><h6><p class="text-right"><a href="/deletekeeper/{{keep.id}}/">Удалить</a></p></h6>
<div style="background: #ffe; border: 1px solid #2199e8; padding: 10px;">
<p style="word-break: break-all;">{{keep.keep_text|safe}}</p>
    </div>
<h4>{{keep.keep_data}}</h4>

    <hr>
{% endtimezone %}
<div class="large-offset-1 large-11 columns">
<p>Комментарий:</p>
{% for feedback in feedbacks %}
    {% load tz %}
    {% timezone "Europe/Moscow" %}
    <div>
            <h6><p class="text-right">Пользователь: {{feedback.feedback_from}} {{feedback.feedback_data}}</p></h6>
            <div style="background: #ffe; border: 1px solid #DCDCDC; padding: 10px;"><p style="word-break: break-all;" class="text-left">{{feedback.feedback_text}}</p></div>
    </div>
    {% endtimezone %}
{%endfor%}
    <div class="row">
        <div class="large-3 large-offset-5 columns">
            <ul class="pagination">
                {% if feedbacks.has_previous %}
                    <li class="arrow"><a href="/keeper/get/{{keep.id}}/{{ feedbacks.previous_page_number }}/">&laquo;</a></li>
                {% else %}
                    <li class="arrow unavailable"><a href="">&laquo;</a></li>
                {% endif %}
                {% for page in feedbacks.paginator.page_range %}
                    {% if page == feedbacks.number %}
                        <li class="current"><a href="/keeper/get/{{keep.id}}/{{ page }}/">{{ page }}</a></li>
                    {% else %}
                        <li><a href="/keeper/get/{{keep.id}}/{{ page }}/">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if feedbacks.has_next %}
                    <li class="arrow"><a href="/keeper/get/{{keep.id}}/{{ feedbacks.next_page_number }}/">&raquo;</a></li>
                {% else %}
                    <li class="arrow unavailable"><a href="">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    <form action="/keeper/addfeedback/{{keep.id}}/" method="post">
        {% csrf_token %}
        {{ FedForm }}
        <input type="submit" class="button" value="Добавить комментарий">
    </form>
    </div>
    </div>
{% endblock %}

workite/keeper/templates/KeeperMarkerEdit.html
<!--{% extends 'main.html' %}-->

<!--{% block keeper %}-->
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static "/css/foundation.css" %}">

<script src="{% static "lib/jquery-1.8.3.min.js" %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static "src/jquery.maskedinput.js" %}" type="text/javascript"></script>
<script src="{% static "js/jquery-ui.min.js" %}"></script>
	<link type="text/css" rel="stylesheet" href="{% static "css/jquery-ui.css" %}"/>


<script type="text/javascript">
jQuery(function($){
   $("#id_searchlabelkeeper_marker").mask("*?*****************************", {placeholder:""});
});
</script>
    <div class="columns  large-2">
    <form action="/keepermarkeredit_add/" method="post">
        {% csrf_token %}
        {{ SearchLabelKeeperForm }}
        <input type="submit" class="button" value="добавить поисковую метку">
    </form>
    </div>
<div class="row">
{% for marker in SearchLabelKeepers %}
    <div class="columns large-2 large-offset-1">
    <p style="word-break: break-all;">{{marker.searchlabelkeeper_marker}}</p> <p class="text-right"><a href="/keepermarkeredit_delete/{{marker.id}}/">Удалить</a></p><p class="text-right"><a href="/keepermarkereedit/{{marker.id}}/">Изменить</a></p></h6>
    <hr>
     </div>
{% endfor %}
</div>

<!--{% endblock %}-->

workite/keeper/templates/NewKeeper.html
{% extends 'main.html' %}
{% load staticfiles %}
{% block keeper %}

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
        <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>


<script>
        $(document).ready(function() {
                $("#button_load_earchLabelKeepers").click(function () {
                        $("#id_SearchLabelKeepers").load(location.href + " #id_SearchLabelKeepers>*", "");

                });
        });
</script>
<div class="medium-2 large-offset-0 columns">
                <button id="button_load_earchLabelKeepers" class="button">Обновить список</button>
</div>
<div class="row">
    <form action="/addkeeper/" method="post">

        {% csrf_token %}

        <div class="columns medium-2 large-offset-0 ">
                <a href="/keepermarkeredit/" class="button" onclick="newMyWindow1(this.href); return false;">Список тегов</a>
                <script>
                function newMyWindow1(href) {
                  var d = document.documentElement,
                      h = 500,
                      w = 500,
                      myWindow = window.open(href, 'myWindow', 'scrollbars=1,height='+Math.min(h, screen.availHeight)+',width='+Math.min(w, screen.availWidth)+',left='+Math.max(0, ((d.clientWidth - w)/2 + window.screenX))+',top='+Math.max(0, ((d.clientHeight - h)/2 + window.screenY)));

                      // абзац для Chrome
                      if (myWindow.screenY >= (screen.availHeight - myWindow.outerHeight)) {myWindow.moveTo(myWindow.screenX, (screen.availHeight - myWindow.outerHeight))};
                      if (myWindow.screenX >= (screen.availWidth - myWindow.outerWidth)) {myWindow.moveTo((screen.availWidth - myWindow.outerWidth), myWindow.screenY)};

                }
                </script>
        </div>
        <div id="id_SearchLabelKeepers">
        <select size="4" multiple="multiple" name="search_attribute">
            {% for marker in SearchLabelKeepers %}
                <option {%if marker.searchlabelkeeper_marker in search_attribute %}
                        selected
                        {%endif%}
                        value="{{marker.searchlabelkeeper_marker}}">{{marker.searchlabelkeeper_marker}}</option>
            {% endfor %}
        </select>
        </div>
        <div>
            <p style="word-break: break-all;">Название статьи: </p>
            <input type="text" required="" name="keep_title" maxlength="200" id="id_keep_title">
        </div>
        <div>
            {{KeeForm}}
        </div>
        <input type="submit" class="button" value="Добавить статью">
        <h6><p class="text-right"><a href="/keepermarkeredit/" target="_blank">Список тегов</a> </p> </h6>
    </form>
</div>
{% endblock %}

workite/keeper/templates/test_select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <form action="/test_select/" method="post">{% csrf_token %}
     Логическое И
   <p><select size="5" multiple="multiple" name="search_attribute">
       {% for marker in SearchLabelKeepers %}
            <option {%if marker in tut %}
                        selected
                    {%endif%}
                    value="{{marker.searchlabelkeeper_marker}}">{{marker.searchlabelkeeper_marker}}</option>

       {% endfor %}
   </select></p>
     Логическое ИЛИ
       <p><select size="5" multiple="multiple" name="hero2[]">
       {% for marker in SearchLabelKeepers %}
            <option {%if marker in tut_2 %}
                        selected
                    {%endif%}
                    value="{{marker.searchlabelkeeper_marker}}">{{marker.searchlabelkeeper_marker}}</option>

       {% endfor %}
   </select></p>
     <p><b>Строка поиска:</b><br><input type="text" size="40" name="search_text"></p>
 <p><input type="checkbox" name="search_and_only" value="only_and"> Выбрать только указанные</p>
   <p><input type="submit" value="Отправить"></p>
  </form>
    {% for tut1 in tut %}
        {{tut1}}
        <hr>
    {% endfor %}
    {% for tut2 in tut_2 %}
        {{tut2}}
        <hr>
    {% endfor %}
    {% for test_ in test %}
       id =  {{  test_.keeper_id }}
    {% endfor %}
{#    {{ test }}#}
    <div><h2>qss{{ test2 }}</h2></div>
    {{ grups_true }}
        {{ grups }}
    {% for keep in keeps %}
    {% load tz %}
    {% timezone "Europe/Moscow" %}
    <h6><a href="/keeper/get/{{ keep.id }}">{{keep.keep_title}}</a></h6>
    <p style="word-break: break-all;">{{keep.keep_text|safe}}</p>
    <!--  {{ data|safe }} отключить экранирование-->
    <h2>Поисковые теги {{keep.keep_hashTag}}</h2>
    <h4>{{keep.keep_data}}</h4>
    <hr>
    {% endtimezone %}
{% endfor %}
</body>
</html>

workite/keeper/templates/thekeepermarkereedit.html
{% extends 'main.html' %}
{% block keeper %}
{% load staticfiles %}
<script src="{% static "lib/jquery-1.8.3.min.js" %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static "src/jquery.maskedinput.js" %}" type="text/javascript"></script>
<script src="{% static "js/jquery-ui.min.js" %}"></script>
	<link type="text/css" rel="stylesheet" href="{% static "css/jquery-ui.css" %}"/>


<script type="text/javascript">
jQuery(function($){
   $("#id_searchlabelkeeper_marker").mask("*?*****************************", {placeholder:""});
});
</script>
    <form action="/keepermarkereedit/{{marker_id}}/" method="post">
        {% csrf_token %}
        {{ SearchLabelKeeperForm }}
        <input type="submit" class="button" value="Изменить поисковую метку">
    </form>
{% endblock %}